name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-and-compile-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        id: install_rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check formatting
        if: always() && steps.install_rust.outcome == 'success'
        run: cargo fmt -- --check --config group_imports=StdExternalCrate

      - name: Run Clippy linter
        if: always() && steps.install_rust.outcome == 'success'
        run: cargo clippy --tests -- -D warnings -W clippy::pedantic

      - name: Cargo check
        if: always() && steps.install_rust.outcome == 'success'
        run: cargo check

      - name: Lint Markdown files (.md)
        if: always() && steps.install_rust.outcome == 'success'
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: "**/*.{md,markdown}"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --summary-only
